
version: '3'

services:
   db:
     build:
       dockerfile: ./dockerfiles/database/Dockerfile
       context: .
     image: mysql:5.5
     restart: always
     container_name: database
     networks:
      - netapp
     volumes:
       - db_data:/var/lib/mysql
       - ./database/scripts:/docker-entrypoint-initdb.d
       - /etc/localtime:/etclocaltim:ro
     environment:
       MYSQL_ROOT_PASSWORD: Root@1001
       MYSQL_USER: notes-api
       MYSQL_PASSWORD: notes-api

   node:
     build:
       dockerfile: ./dockerfiles/app/Dockerfile
       context: .
     image: node
     restart: always
     container_name: appserver
     networks:
      - netapp
     user: "node"
     working_dir: /home/node/app
     environment:
       - NODE_ENV=production
     volumes:
       - ./app:/home/node/app
       - /etc/localtime:/etc/localtime:ro
     expose:
       - "8080" 
     depends_on:
       - db
     command: "npm start"

   web:
     build:
       dockerfile: ./dockerfiles/web/Dockerfile
       context: .
     image: nginx
     restart: always
     container_name: webserver
     networks:
      - netapp 
     volumes:
       - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "80:80"
     depends_on:
       - node
     environment:
       - NGINX_HOST=localhost
       - NGINX_PORT=80
     command: "nginx -g 'daemon off;'"

   php:
     image:  phpmyadmin/phpmyadmin:4.7.0-1
     restart: always
     container_name: phpmyadmin
     networks:
      - netapp
     volumes:
       - /etc/localtime:/etclocaltim:ro
     environment:
       - PMA_HOST=db
     ports:
       - "8010:80"
     depends_on:
       - db

networks:
  netapp:
    external:
      name: netapp

volumes:
    db_data:
