#Imagem para uso da API Notes
FROM mysql:5.5 AS mysqlapi
MAINTAINER Edson Nascimento Lima <enlimarj@gmail.com>
RUN apt-get update && apt-get install iputils-ping -y \
net-tools \
vim \
&& rm -rf /var/lib/apt/lists/*
